# [AI Generated] Data: 19/03/2024
# Descrição: Configuração simplificada do Netlify para deploy
# Gerado por: Cursor AI
# Versão: Next.js 14.2.5

[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
